---
####################################################################
# Hitachi Storage Provisioning Playbooks for SAP HANA
# Author: Hitachi Vantara SAP Engineering Team
# Version: v1.0
# Date: November 2025
#
# Summary: Configures storage port settings including security,
# fabric mode, connection type, and port speed.
####################################################################

####################################################################
# Storage Port  Playbook
####################################################################
- name: Storage Port Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ~/playbooks/ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables_modify.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Modify storage port settings using port id
    ####################################################################
    - name: Modify Storage Port Security, Connection, Speed and Fabric mode settings of port ids {{storage_port_port_1}}, {{ storage_port_port_2 }}
      hitachivantara.vspone_block.vsp.hv_storage_port:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          port: "{{ item }}"
          enable_port_security: false
          fabric_mode: true
          port_connection: "PtoP"
          port_speed: "{{ portspeed }}"
            
      loop:
        - "{{ storage_port_port_1 }}"
        - "{{ storage_port_port_2 }}"
      register: result
      ignore_errors: true

