---
####################################################################
# Hitachi Storage Provisioning Playbooks for SAP HANA
# Author: Hitachi Vantara SAP Engineering Team
# Version: v1.0
# Date: November 2025
#
# Summary: Retrieves hostgroup information for specific ports
# defined in variables, returning details like mapped WWNs and LDEVs.
####################################################################

####################################################################
# Hostgroup Facts Playbook
####################################################################
- name: Hostgroup Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ~/playbooks/ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables_facts.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Get all hostgroups
    ####################################################################
    - name: Get hostgroups for custom ports
      hitachivantara.vspone_block.vsp.hv_hg_facts:
        connection_info: "{{ connection_info }}"
        spec:
          query: ['wwns', 'ldevs']
          #name: 'test-ansible-hg-1'
          ports: ['{{ storage_port_port_1 }}', '{{ storage_port_port_2 }}']
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

