---
####################################################################
# Hitachi Storage Provisioning Playbooks for SAP HANA
# Author: Hitachi Vantara SAP Engineering Team
# Version: v1.0
# Date: November 2025
#
# Summary: Retrieves and lists all LDEVs (PVOLs) residing in a
# specific storage pool identified by its Pool ID.
####################################################################

####################################################################
# LDEV Facts Playbook
####################################################################
- name: Logical Device Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ~/playbooks/ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables_facts.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Get ldevs from Pool ID
    ####################################################################
    - name: Get PVOL details using pool id
      hitachivantara.vspone_block.vsp.hv_ldev_facts:
        connection_info: "{{ connection_info }}"
        spec:
          #parity_group_id: "1-3"
          pool_id: "{{ target_pool_id }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result


    - name: Debug LDEV ID and Volume Name (PVOL)
      ansible.builtin.debug:
        msg: "LDEV_ID: {{ item.ldev_id }}, Volume_Name: {{ item.name }}"
      loop: "{{ result.ansible_facts.volumes }}"
      loop_control:
        label: "{{ item.name }}"

