---
####################################################################
# Hitachi Storage Provisioning Playbooks for SAP HANA
# Author: Hitachi Vantara SAP Engineering Team
# Version: v1.0
# Date: November 2025
#
# Summary: Retrieves and displays configuration facts for a single
# specified Parity Group ID.
####################################################################

####################################################################
# Parity Group Facts Playbook
####################################################################
- name: Parity Group Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ~/playbooks/ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables_facts.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Get one paritygroup
    ####################################################################
    - name: Get one paritygroup
      hitachivantara.vspone_block.vsp.hv_paritygroup_facts:
        connection_info: "{{ connection_info }}"
        spec:
          parity_group_id: "{{ parity_group_id }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
